### ISSUE TITLE
info for run this project

### ISSUE THREAD

**Issue by multivoltage** [allevo/seqflow-js#16]
I saw you job/meet :).

Maybe I want to contribute but it' s hard for me to:
- undestand what version of pnpm
- undestand what version of node

I tried with pnpm 8.x and 9.x under node 20.
OK with `pnpm install` but faild with `pnpm build` with
`TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts"`

Can you add some details or maybe a PR with for example:
"packageManager" inside `package.json` or `.nvm` file file for example.

Thanks

**Comment by allevo** [comment]
Try the following commands:

```bash
git clone https://github.com/allevo/seqflow-js
cd seqflow-js
npx pnpm@9 install
cd packages/seqflow-js
npx pnpm@9 install
npx pnpm@9 test
npx pnpm@9 build
cd ../../examples/e-commerce
npx pnpm@9 install
npx pnpm@9 test
npx pnpm@9 start
```

you can avoid `npx pnpm@9 ...` if you use `pnpm` at version 9.
``` bash
% node -v
v20.11.1
```

Let me know.

**Comment by multivoltage** [comment]
With pnpm 9.x (installed yesterday) and node 20 I have the same error:
`TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts"`

**Comment by allevo** [comment]
Can you share more information about your environment?
From a fresh checkout, which step did you take? I mean, also `cd` and similar.

**Comment by multivoltage** [comment]
```
node: 20.4.0 (installed with nvm)
pnpm: 9.1.1 (installed with homebrew)
macbook pro 2019 (intel)
```

1. forked repo
2. cloned my repo
3. nvm use 20
4. pnpm install
5. pnpm run build
[build.log](https://github.com/allevo/seqflow-js/files/15391737/build.log)

**Comment by allevo** [comment]
Update your node version. `node --import tsx` is introduced later.
I'm using `v20.11.1`.

**Comment by multivoltage** [comment]
it works.
maybe to add 
```
  "engines": {
    "node": ">=20.x"
  }
```
in `package.json`?
